package app.bpartners.geojobs.model.geometry.polygon;

import static app.bpartners.geojobs.model.geometry.GeometryFactory.geometryFactory;

import java.util.function.Supplier;
import lombok.AllArgsConstructor;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.LineString;
import org.locationtech.jts.geom.LinearRing;
import org.locationtech.jts.geom.Polygon;

/*
 * Mostly generated by ChatGPT
 */
@AllArgsConstructor
public class EnvelopeAsPolygon implements Supplier<Polygon> {

  private final LineString line;

  @Override
  public Polygon get() {
    var envelope = line.getEnvelope().getEnvelopeInternal();
    Coordinate[] coordinates =
        new Coordinate[] {
          new Coordinate(envelope.getMinX(), envelope.getMinY()), // Bottom-left
          new Coordinate(envelope.getMaxX(), envelope.getMinY()), // Bottom-right
          new Coordinate(envelope.getMaxX(), envelope.getMaxY()), // Top-right
          new Coordinate(envelope.getMinX(), envelope.getMaxY()), // Top-left
          new Coordinate(envelope.getMinX(), envelope.getMinY()) // Close the ring
        };

    LinearRing shell = geometryFactory.createLinearRing(coordinates);
    return geometryFactory.createPolygon(shell);
  }
}
