package app.bpartners.geojobs.model.geometry.polygon;

import static app.bpartners.geojobs.model.geometry.GeometryFactory.geometryFactory;

import java.util.function.Supplier;
import lombok.AllArgsConstructor;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.LineString;
import org.locationtech.jts.geom.Polygon;
import org.locationtech.jts.geom.prep.PreparedGeometry;
import org.locationtech.jts.geom.prep.PreparedGeometryFactory;

/*
 * Mostly generated by ChatGPT
 */
@AllArgsConstructor
public class LongestInteriorLine implements Supplier<LineString> {

  private final Polygon polygon;

  // Check if a line is fully inside the polygon
  private static boolean isLineInsidePolygon(Polygon polygon, LineString line) {
    PreparedGeometry preparedPolygon = PreparedGeometryFactory.prepare(polygon);
    return preparedPolygon.contains(line);
  }

  @Override
  public LineString get() {
    Coordinate[] coordinates = polygon.getExteriorRing().getCoordinates();
    LineString longestLine = createLine(coordinates[0], coordinates[1]);
    double maxLength = longestLine.getLength();

    // Iterate through all pairs of coordinates
    for (int i = 0; i < coordinates.length; i++) {
      for (int j = i + 1; j < coordinates.length; j++) {
        Coordinate start = coordinates[i];
        Coordinate end = coordinates[j];

        // Perform binary search to ensure the line is fully inside
        LineString candidateLine = createLine(start, end);
        if (isLineInsidePolygon(polygon, candidateLine)) {
          double length = candidateLine.getLength();
          if (length > maxLength) {
            maxLength = length;
            longestLine = candidateLine;
          }
        }
      }
    }
    return longestLine;
  }

  // Create a LineString from two coordinates
  private static LineString createLine(Coordinate start, Coordinate end) {
    Coordinate[] lineCoordinates = new Coordinate[] {start, end};
    return geometryFactory.createLineString(lineCoordinates);
  }
}
