package app.bpartners.geojobs.model.geometry.polygon;

import static app.bpartners.geojobs.model.geometry.GeometryFactory.geometryFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;
import lombok.AllArgsConstructor;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Polygon;

/*
 * Mostly generated by ChatGPT
 */
@AllArgsConstructor
public class MaximalPolygonFromEdges implements Supplier<Polygon> {
  private final Polygon polygon;
  private final int m;

  @Override
  public Polygon get() {
    Coordinate[] originalCoords = polygon.getCoordinates();
    int n = originalCoords.length - 1; // Exclude the closing coordinate

    // Generate all subsets of m edges
    List<List<Coordinate>> subsets = generateSubsets(originalCoords, n, m);

    // Track the polygon with the maximum area
    double maxArea = 0;
    Polygon maxPolygon = null;

    for (List<Coordinate> subset : subsets) {
      // Ensure the subset forms a valid closed polygon
      subset.add(subset.getFirst()); // Close the ring
      Polygon candidate = geometryFactory.createPolygon(subset.toArray(new Coordinate[0]));

      // Check if it's valid
      if (candidate.isValid() && candidate.getArea() > maxArea) {
        maxArea = candidate.getArea();
        maxPolygon = candidate;
      }
    }

    return maxPolygon;
  }

  /**
   * Generates all subsets of m edges from the original polygon's coordinates.
   *
   * @param coordinates the input coordinates of the polygon
   * @param n the number of edges in the original polygon
   * @param m the desired number of edges in the subset
   * @return a list of subsets, each containing m edges
   */
  private static List<List<Coordinate>> generateSubsets(Coordinate[] coordinates, int n, int m) {
    List<List<Coordinate>> subsets = new ArrayList<>();
    generateSubsetsHelper(coordinates, n, m, 0, new ArrayList<>(), subsets);
    return subsets;
  }

  /** Helper function to recursively generate subsets. */
  private static void generateSubsetsHelper(
      Coordinate[] coordinates,
      int n,
      int m,
      int index,
      List<Coordinate> current,
      List<List<Coordinate>> subsets) {
    if (current.size() == m) {
      subsets.add(new ArrayList<>(current));
      return;
    }
    if (index >= n) {
      return;
    }

    // Include the current coordinate
    current.add(coordinates[index]);
    generateSubsetsHelper(coordinates, n, m, index + 1, current, subsets);

    // Exclude the current coordinate
    current.remove(current.size() - 1);
    generateSubsetsHelper(coordinates, n, m, index + 1, current, subsets);
  }
}
