package app.bpartners.geojobs.model.geometry.polygon;

import java.util.function.Supplier;
import lombok.AllArgsConstructor;
import lombok.SneakyThrows;
import org.locationtech.jts.algorithm.ConvexHull;
import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.Envelope;
import org.locationtech.jts.geom.Geometry;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.Polygon;
import org.locationtech.jts.geom.util.AffineTransformation;

/*
 * Mostly generated by ChatGPT
 */
@AllArgsConstructor
public class OrientedBoundingBox implements Supplier<Polygon> {

  private final Polygon polygon;
  private static final GeometryFactory geomFactory = new GeometryFactory();

  @SneakyThrows
  public Polygon get() {
    Geometry convexHull = new ConvexHull(polygon).getConvexHull();
    if (!(convexHull instanceof Polygon)) {
      throw new IllegalArgumentException("Convex hull computation failed to produce a polygon.");
    }

    Coordinate[] convexHullCoords = convexHull.getCoordinates();
    Polygon orientedBoundingBox = null;
    double minArea = Double.MAX_VALUE;

    // Iterate through edges of the convex hull
    for (int i = 0; i < convexHullCoords.length - 1; i++) {
      Coordinate p1 = convexHullCoords[i];
      Coordinate p2 = convexHullCoords[i + 1];

      // Compute the angle of the edge relative to the x-axis
      double angle = Math.atan2(p2.y - p1.y, p2.x - p1.x);

      // Rotate the polygon to align the edge with the x-axis
      AffineTransformation rotation = AffineTransformation.rotationInstance(-angle, 0, 0);
      Geometry rotatedPolygon = rotation.transform(polygon);

      // Compute the bounding box of the rotated polygon
      Envelope envelope = rotatedPolygon.getEnvelopeInternal();
      double area = envelope.getWidth() * envelope.getHeight();

      // Check if this is the smallest bounding box so far
      if (area < minArea) {
        minArea = area;

        // Transform the envelope back to the original continuationOrientation
        Coordinate[] boxCoords =
            new Coordinate[] {
              new Coordinate(envelope.getMinX(), envelope.getMinY()),
              new Coordinate(envelope.getMaxX(), envelope.getMinY()),
              new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
              new Coordinate(envelope.getMinX(), envelope.getMaxY()),
              new Coordinate(envelope.getMinX(), envelope.getMinY()) // Close the ring
            };

        Polygon boundingBox = geomFactory.createPolygon(geomFactory.createLinearRing(boxCoords));
        orientedBoundingBox = (Polygon) rotation.getInverse().transform(boundingBox);
      }
    }

    return orientedBoundingBox;
  }
}
